import {it,expect} from 'vitest';
import {controlledProvider} from '../src/model-controls.ts';import {createAssistantMessageEventStream} from '@earendil-works/pi-ai';
function source(){return {id:'retry-'+Math.random(),stream(_m:any,_c:any,o:any){const s=createAssistantMessageEventStream();void(async()=>{try{const r=await o.fetch('https://model.example/v1',{method:'POST',body:'{"same":"request"}'});if(!r.ok)throw Error('not ok');s.push({type:'done',reason:'stop',message:{role:'assistant',content:[],usage:{totalTokens:1}}} as any);}catch{s.push({type:'error',reason:'error',error:{errorMessage:'failed'}} as any);}finally{s.end();}})();return s;}};}
it('429在同一次模型请求内退避，保留请求体，不重放已执行工具',async()=>{let calls=0;const bodies:string[]=[];const p=controlledProvider(source(),{retryCount:2,retryBaseMs:1,timeoutMs:1000});const result=await p.stream({id:'x',maxTokens:1},{},{fetch:async(_i:any,init:any)=>{calls++;bodies.push(init.body);return calls===1?new Response('{}',{status:429,headers:{'Retry-After':'0'}}):new Response('{}');}}).result();expect(calls).toBe(2);expect(bodies).toEqual(['{"same":"request"}','{"same":"request"}']);expect(result.errorMessage).toBeUndefined();});
it('Retry-After等待可以取消，不继续额外出网',async()=>{let calls=0;const c=new AbortController(),p=controlledProvider(source(),{retryCount:3,retryBaseMs:1,timeoutMs:1000});const stream=p.stream({id:'x',maxTokens:1},{},{signal:c.signal,fetch:async()=>{calls++;queueMicrotask(()=>c.abort());return new Response('{}',{status:429,headers:{'Retry-After':'30'}});}});expect((await stream.result()).errorMessage).toBeTruthy();expect(calls).toBe(1);});
it('非限流客户端错误不重试',async()=>{let calls=0;await controlledProvider(source(),{retryCount:3}).stream({id:'x',maxTokens:1},{},{fetch:async()=>{calls++;return new Response('{}',{status:400});}}).result();expect(calls).toBe(1);});
function moderatedSource(text:string){return {id:'moderation-'+Math.random(),stream(){const s=createAssistantMessageEventStream();queueMicrotask(()=>{s.push({type:'text_delta',delta:text} as any);s.push({type:'done',reason:'stop',message:{role:'assistant',content:[{type:'text',text}],usage:{totalTokens:2}}} as any);s.end();});return s;}};}
it('审核拒绝时不泄露任何文本事件并记录失败',async()=>{const metrics:any[]=[];const p=controlledProvider(moderatedSource('待审核正文'),{checkOutput:async()=>{throw Error('blocked');},onMetric:m=>metrics.push(m)});const events:any[]=[];for await(const e of p.stream({id:'x'},{},{}))events.push(e);expect(events.map(e=>e.type)).toEqual(['error']);expect(JSON.stringify(events)).not.toContain('待审核正文');expect(metrics[0].status).toBe('moderation_error');});
it('审核通过后按顺序释放且只审核一次',async()=>{const checked:string[]=[];const p=controlledProvider(moderatedSource('正常正文'),{checkOutput:async t=>{checked.push(t);}});const types:string[]=[];for await(const e of p.stream({id:'x'},{},{}))types.push(e.type);expect(types).toEqual(['text_delta','done']);expect(checked).toEqual(['正常正文']);});
it('审核缓冲超过上限即关闭，不输出未审核文本',async()=>{const p=controlledProvider(moderatedSource('x'.repeat(9*1024*1024)),{checkOutput:async()=>{throw Error('should not call');}});const types:string[]=[];for await(const e of p.stream({id:'x'},{},{}))types.push(e.type);expect(types).toEqual(['error']);});
