import { afterEach, describe, expect, it } from 'vitest';
import { mkdtempSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createPermissionGate, type ToolDecision } from '@tao/core';
import { detectSensitiveInput, filterTools, governToolRequest, validateToolPolicy, withToolGovernance, type GovernanceRequest } from '../src/tool-governance.ts';
const roots:string[]=[];
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
function root(){const r=mkdtempSync(join(tmpdir(),'tao-governance-'));roots.push(r);return r;}
function request(toolName:string,args:unknown={}):GovernanceRequest{return {toolName,args,tenant:{tenantId:'tenant',workspaceId:'workspace',userId:'alice'},taskId:'task-a'};}
const rules=(...items:unknown[])=>({SECURITY_TOOL_RULES_JSON:JSON.stringify(items)});
describe('工具治理只收紧原门',()=>{
 it('默认无附加授权；基线拒绝优先于任何确认规则',async()=>{const dir=root();expect(governToolRequest(request('read_document',{path:'a.txt'}),{},dir)).toBeUndefined();const gate=withToolGovernance(createPermissionGate({workspace:dir,policies:[]}),()=>rules({tool:'*',decision:'confirm'}),dir);expect((await gate(request('read_document'))).kind).toBe('block');});
 it('原门路径拒绝和高危确认不可被空配置或未命中规则降级',async()=>{const dir=root(),base=createPermissionGate({workspace:dir,policies:[{tool:'read_document',pathParams:['path']},{tool:'sandbox_execute',requiresConfirm:true}]});const gate=withToolGovernance(base,()=>rules({tool:'sandbox_execute',decision:'deny',commandPrefix:'rm -rf'}),dir);expect((await gate(request('read_document',{path:'/etc/passwd'}))).kind).toBe('block');expect((await gate(request('sandbox_execute',{language:'bash',code:'echo ok'}))).kind).toBe('confirm');});
 it('精确授权外部输入保留主门allow，邻接未授权文件仍被主门拒绝',async()=>{const dir=root(),external=root(),allowed=join(external,'input.md');writeFileSync(allowed,'authorized');const base=createPermissionGate({workspace:dir,policies:[{tool:'read_document',pathParams:['path']}],allowedFiles:[allowed]});const gate=withToolGovernance(base,()=>rules({tool:'read_document',decision:'confirm',pathPrefix:'output'}),dir);expect((await gate(request('read_document',{path:allowed}))).kind).toBe('allow');expect((await gate(request('read_document',{path:join(external,'other.md')}))).kind).toBe('block');});
 it('禁用名单与无条件deny隐藏工具，条件deny仅逐次判断且deny优先',()=>{const dir=root(),v={...rules({tool:'write_document',decision:'deny',pathPrefix:'restricted'},{tool:'web_search',decision:'deny'},{tool:'read_document',decision:'confirm'},{tool:'read_document',decision:'deny'}),SECURITY_DISABLED_TOOLS:'sandbox_execute'};expect(filterTools([{name:'write_document'},{name:'web_search'},{name:'sandbox_execute'}],v)).toEqual([{name:'write_document'}]);expect(governToolRequest(request('read_document'),v,dir)?.kind).toBe('block');expect(governToolRequest(request('sandbox_execute'),v,dir)?.kind).toBe('block');});
 it('禁止allow、未知字段、非法路径与命令许可配置，执行时错误关闭',()=>{for(const rule of [{tool:'x',decision:'allow'},{tool:'x',decision:'deny',extra:true},{tool:'x',decision:'deny',pathPrefix:'../private'},{tool:'x',decision:'deny',pathPrefix:'/etc'},{tool:'x',decision:'deny',commandPrefix:'rm; echo ok'}])expect(()=>validateToolPolicy(rules(rule))).toThrow();expect(governToolRequest(request('x'),{SECURITY_TOOL_RULES_JSON:'not json'},root())?.kind).toBe('block');});
 it('相对路径与真实任务绝对路径等价，按目录边界匹配而非字符串相似',()=>{const dir=root(),v=rules({tool:'edit_document',decision:'confirm',pathPrefix:'protected'});expect(governToolRequest(request('edit_document',{path:'protected/a.md'}),v,dir)?.kind).toBe('confirm');expect(governToolRequest(request('edit_document',{path:join(dir,'protected','a.md')}),v,dir)?.kind).toBe('confirm');expect(governToolRequest(request('edit_document',{path:'protected-old/a.md'}),v,dir)).toBeUndefined();expect(governToolRequest(request('edit_document',{path:'other/../protected/a.md'}),v,dir)?.kind).toBe('confirm');});
 it('越界或链接路径不匹配逻辑pathPrefix，授权仍由原门决定',()=>{const dir=root(),outside=root();mkdirSync(join(outside,'existing'));writeFileSync(join(outside,'existing','a.md'),'private');symlinkSync(join(outside,'existing'),join(dir,'link'));symlinkSync(join(outside,'missing'),join(dir,'dangling'));for(const path of ['/etc/passwd','../outside','C:\\secret','file:///etc/passwd','link/a.md','link/new.md','dangling'])expect(governToolRequest(request('edit_document',{path}),rules({tool:'edit_document',decision:'confirm',pathPrefix:''}),dir)).toBeUndefined();});
 it('沙箱/workspace映射逻辑路径，不能以相似目录前缀或..逃逸',()=>{const dir=root(),v=rules({tool:'sandbox_files',decision:'deny',pathPrefix:'output/private'});expect(governToolRequest(request('sandbox_files',{path:'/workspace/output/private/a.txt'}),v,dir)?.kind).toBe('block');expect(governToolRequest(request('sandbox_files',{path:'/workspace/output/public/a.txt'}),v,dir)).toBeUndefined();for(const path of ['/workspace2/file','/workspace/../../etc/passwd'])expect(governToolRequest(request('sandbox_files',{path}),v,dir)).toBeUndefined();});
 it('命令前缀匹配token边界与复合命令，仅拒绝或提高确认',async()=>{const dir=root(),v=rules({tool:'sandbox_execute',decision:'deny',commandPrefix:'rm -rf'});for(const code of ['rm -rf output','echo done; rm -rf output','echo done && rm -rf output'])expect(governToolRequest(request('sandbox_execute',{language:'bash',code}),v,dir)?.kind).toBe('block');expect(governToolRequest(request('sandbox_execute',{language:'bash',code:'rmdir output'}),v,dir)).toBeUndefined();expect(governToolRequest(request('sandbox_execute',{language:'bash',code:'rm -rfoo output'}),v,dir)).toBeUndefined();const base=async():Promise<ToolDecision>=>({kind:'confirm',reason:'沙箱代码默认确认'});expect((await withToolGovernance(base,()=>v,dir)(request('sandbox_execute',{language:'bash',code:'bash -c "echo ok"'}))).kind).toBe('confirm');});
 it('按开关提高写操作确认，不把只读文件操作升级为写操作',()=>{const dir=root(),v={SECURITY_CONFIRM_WRITES:'true'};expect(governToolRequest(request('write_presentation',{outputName:'deck.pptx'}),v,dir)?.kind).toBe('confirm');expect(governToolRequest(request('sandbox_files',{action:'write',path:'output/a.txt'}),v,dir)?.kind).toBe('confirm');expect(governToolRequest(request('sandbox_files',{action:'read',path:'inputs/a.txt'}),v,dir)).toBeUndefined();});
 it('敏感检测只返回类型和位置，不回显值或任意字段名，默认提示而非拦截',()=>{const dir=root(),credential='sk-'+('x'.repeat(24)),input={args:{apiKey:credential,[credential]:'safe',text:'-----BEGIN PRIVATE KEY-----'}};const findings=detectSensitiveInput(input);expect(findings.some(f=>f.type==='access-token')).toBe(true);expect(findings.some(f=>f.type==='private-key')).toBe(true);expect(JSON.stringify(findings)).not.toContain(credential);expect(findings.every(f=>Object.keys(f).every(k=>['type','location','offset'].includes(k)))).toBe(true);expect(governToolRequest(request('mcp_call',input),{},dir)).toBeUndefined();expect(governToolRequest(request('mcp_call',input),{SECURITY_SENSITIVE_INPUT_MODE:'block'},dir)?.kind).toBe('block');expect(detectSensitiveInput({apiKey:'${API_KEY}',password:'<REDACTED>'})).toEqual([]);});
 it('嵌套图片输入参与路径规则，远程MCP路径不自动当作宿主文件',()=>{const dir=root(),v=rules({tool:'write_presentation',decision:'deny',pathPrefix:'private'});expect(governToolRequest(request('write_presentation',{slides:[{imagePath:'private/chart.png'}]}),v,dir)?.kind).toBe('block');expect(governToolRequest(request('mcp_call',{arguments:{path:'/remote/item'}}),{},dir)).toBeUndefined();});
});
