import { unzipSync, strFromU8 } from 'fflate';
import { createHash } from 'node:crypto';
import { afterEach, describe, expect, it } from 'vitest';
import { createServer, type Server } from 'node:http';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Role, type TenantContext, type StoredTask, type TaskEvent } from '@tao/core';
import { ResourceCatalog } from '../src/resources.ts';
import { createWorkbenchHandler, WorkbenchStore, type WorkbenchInput } from '../src/workbench.ts';

const tenant:TenantContext={tenantId:'test',workspaceId:'workspace',userId:'alice'};
const roots:string[]=[],servers:Server[]=[];
afterEach(async()=>{for(const s of servers.splice(0))await new Promise<void>(r=>s.close(()=>r()));for(const p of roots.splice(0))rmSync(p,{recursive:true,force:true});});
async function fixture(){
 const root=mkdtempSync(join(tmpdir(),'tao-workbench-'));roots.push(root);const dir=join(root,'test','workspace');mkdirSync(dir,{recursive:true});
 const catalog=new ResourceCatalog(root),store=new WorkbenchStore(root);let actor:TenantContext|undefined=tenant;let allowWrite=true;
 const inputFiles:WorkbenchInput[]=[];
 const events=[{type:'user_message',taskId:'task-a',seq:1,at:1,text:'请分析资料 ghp_'+ 'a'.repeat(24)},{type:'assistant_message',taskId:'task-a',seq:2,at:2,text:'已完成 github_pat_'+ 'b'.repeat(24)},{type:'step',taskId:'task-a',seq:3,at:3,toolName:'read_file',detail:'完成',args:{secret:'do-not-export-raw-args'}}] as unknown as TaskEvent[];
 const task={taskId:'task-a',conversationId:'conv-a',tenant,title:'任务摘要 token=private-value',status:'SUCCEEDED'} as StoredTask;
 const handler=createWorkbenchHandler({root,catalog,store,authenticate:async()=>actor?{tenant:actor,role:Role.Member}:undefined,authorizeWrite:(_req,res)=>{if(!allowWrite){res.writeHead(403);res.end('{}');}return allowWrite;},events:()=>events,inputs:()=>inputFiles,listTasks:t=>t.tenantId===tenant.tenantId&&t.workspaceId===tenant.workspaceId?[task]:[],members:()=>[{userId:'alice',name:'Alice'},{userId:'bob',name:'Bob'}]});
 const server=createServer(async(req,res)=>{if(!await handler(req,res)){res.writeHead(404);res.end();}});servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address();if(!address||typeof address==='string')throw new Error();
 async function raw(path:string,method='GET',body?:unknown){return fetch(`http://127.0.0.1:${address.port}/api/workbench/${path}`,{method,...(body?{body:JSON.stringify(body),headers:{'Content-Type':'application/json'}}:{})});}
 async function api(path:string,method='GET',body?:unknown){const res=await raw(path,method,body);return {status:res.status,data:await res.json()};}
 return {root,dir,catalog,store,api,raw,inputFiles,events,actor:(t:TenantContext|undefined)=>{actor=t;},write:(v:boolean)=>{allowWrite=v;}};
}
describe('工作台权限与持久化闭环',()=>{
 it('偏好按用户保存，重启后可读；CSRF拒绝后不写入',async()=>{const f=await fixture();expect((await f.api('preferences','PUT',{nickname:'小陶',styleInstructions:'简洁答复'})).status).toBe(200);expect(new WorkbenchStore(f.root).preferences(tenant).nickname).toBe('小陶');f.actor({...tenant,userId:'bob'});expect((await f.api('preferences')).data.nickname).toBe('');f.write(false);expect((await f.api('preferences','PUT',{nickname:'改写'})).status).toBe(403);expect(f.store.preferences({...tenant,userId:'bob'}).nickname).toBe('');});
 it('文件回收与恢复可用，其他用户和符号链接不可变更',async()=>{const f=await fixture();const p=join(f.dir,'note.txt');writeFileSync(p,'hello');f.catalog.registerFile(tenant,p);f.actor({...tenant,userId:'bob'});expect((await f.api('files/batch','POST',{operations:[{action:'trash',name:'note.txt'}]})).data.results[0].ok).toBe(false);expect(existsSync(p)).toBe(true);f.actor(tenant);symlinkSync(p,join(f.dir,'alias.txt'));expect((await f.api('files/batch','POST',{operations:[{action:'rename',name:'alias.txt',newName:'renamed.txt'}]})).data.results[0].ok).toBe(false);expect((await f.api('files/batch','POST',{operations:[{action:'trash',name:'note.txt'}]})).data.results[0].ok).toBe(true);expect(existsSync(p)).toBe(false);const trash=(await f.api('files?trash=true')).data.items[0];expect((await f.api('files/batch','POST',{operations:[{action:'restore',trashId:trash.trashId}]})).data.results[0].ok).toBe(true);expect(readFileSync(p,'utf8')).toBe('hello');});
 it('默认分享需要登录，公开需明确确认，快照脱敏且撤销立即生效',async()=>{const f=await fixture();const privateShare=(await f.api('shares','POST',{taskId:'task-a'})).data;f.actor(undefined);expect((await f.api('shares/'+privateShare.id)).status).toBe(401);f.actor(tenant);expect((await f.api('shares','POST',{taskId:'task-a',public:true})).status).toBe(400);const publicShare=(await f.api('shares','POST',{taskId:'task-a',public:true,confirmPublic:true})).data;f.actor(undefined);const view=await f.api('shares/'+publicShare.id);expect(view.status).toBe(200);expect(JSON.stringify(view.data)).not.toContain('private-value');expect(JSON.stringify(view.data)).not.toContain('tenantId');f.actor(tenant);await f.api('shares/'+publicShare.id,'DELETE');f.actor(undefined);expect((await f.api('shares/'+publicShare.id)).status).toBe(404);});
 it('团队只读成员不能变更，协作成员可整理任务但不能改成员',async()=>{const f=await fixture();const team=(await f.api('teams','POST',{name:'测试空间'})).data.team;await f.api('teams/'+team.id,'PATCH',{members:[{userId:'bob',role:'viewer'}]});f.actor({...tenant,userId:'bob'});expect((await f.api('teams/'+team.id,'PATCH',{taskIds:['task-a']})).status).toBe(403);f.actor(tenant);await f.api('teams/'+team.id,'PATCH',{members:[{userId:'bob',role:'editor'}]});f.actor({...tenant,userId:'bob'});expect((await f.api('teams/'+team.id,'PATCH',{taskIds:['task-a']})).status).toBe(200);expect((await f.api('teams/'+team.id,'PATCH',{members:[]})).status).toBe(403);f.actor({...tenant,workspaceId:'other'});expect((await f.api('teams')).data.teams).toEqual([]);});
 it('文本版本对比读取不可变版本，修订裁定仅产物创建者可做',async()=>{const f=await fixture();const path=join(f.dir,'report.txt');writeFileSync(path,'version one');f.catalog.record(tenant,'task-a',path,[]);writeFileSync(path,'version two');const art=f.catalog.record(tenant,'task-a',path,[]);const diff=await f.api(`artifacts/${art.artifactId}/diff?from=${art.versions[0]!.versionId}&to=${art.versions[1]!.versionId}`);expect(diff.data).toMatchObject({before:'version one',after:'version two'});f.actor({...tenant,userId:'bob'});const comment=(await f.api(`artifacts/${art.artifactId}/comments`,'POST',{text:'补充结论',proposal:true})).data.comment;expect((await f.api(`artifacts/${art.artifactId}/comments/${comment.id}`,'PATCH',{status:'accepted'})).status).toBe(403);f.actor(tenant);expect((await f.api(`artifacts/${art.artifactId}/comments/${comment.id}`,'PATCH',{status:'accepted'})).status).toBe(200);f.actor({...tenant,tenantId:'other'});expect((await f.api(`artifacts/${art.artifactId}/comments`)).status).toBe(404);});
});

describe('分享文件与私有转交包',()=>{
 async function artifactFixture(){const f=await fixture();const path=join(f.dir,'report.html');writeFileSync(path,'<h1>真实产物</h1>');const art=f.catalog.record(tenant,'task-a',path,[]),version=art.versions[0]!;return {...f,art,version,selection:{artifactId:art.artifactId,versionId:version.versionId,sha256:version.sha256}};}
 it('包含文件必须额外确认，且只能选择当前授权任务的产物版本',async()=>{const f=await artifactFixture();expect((await f.api('shares','POST',{taskId:'task-a',includeFiles:true,files:[f.selection]})).status).toBe(400);writeFileSync(join(f.dir,'other.txt'),'other');const other=f.catalog.record(tenant,'task-b',join(f.dir,'other.txt'),[]);expect((await f.api('shares','POST',{taskId:'task-a',includeFiles:true,confirmFiles:true,files:[{artifactId:other.artifactId,versionId:other.versions[0]!.versionId}]})).status).toBe(404);const minimal=(await f.api('shares','POST',{taskId:'task-a',files:[f.selection]})).data;expect((await f.api('shares/'+minimal.id)).data.files).toEqual([]);});
 it('公开token只能下载创建时选定版本，HTML强制附件且新增版本不扩权',async()=>{const f=await artifactFixture();const share=(await f.api('shares','POST',{taskId:'task-a',public:true,confirmPublic:true,includeFiles:true,confirmFiles:true,files:[f.selection]})).data;writeFileSync(join(f.dir,'report.html'),'<h1>后续版本</h1>');const next=f.catalog.record(tenant,'task-a',join(f.dir,'report.html'),[]).versions.at(-1)!;writeFileSync(join(f.dir,'unshared.txt'),'未分享');const other=f.catalog.record(tenant,'task-a',join(f.dir,'unshared.txt'),[]);f.actor(undefined);const download=await f.raw(`shares/${share.id}/files/${f.art.artifactId}/${f.version.versionId}`);expect(download.status).toBe(200);expect(download.headers.get('content-disposition')).toContain('attachment');expect(download.headers.get('x-content-type-options')).toBe('nosniff');expect(download.headers.get('content-type')).toBe('application/octet-stream');expect(await download.text()).toBe('<h1>真实产物</h1>');expect((await f.raw(`shares/${share.id}/files/${f.art.artifactId}/${next.versionId}`)).status).toBe(404);expect((await f.raw(`shares/${share.id}/files/${other.artifactId}/${other.versions[0]!.versionId}`)).status).toBe(404);});
 it('私有分享需要同工作区身份，到期与撤销阻断元数据和文件下载',async()=>{const f=await artifactFixture();const share=(await f.api('shares','POST',{taskId:'task-a',includeFiles:true,confirmFiles:true,files:[f.selection]})).data;const route=`shares/${share.id}/files/${f.art.artifactId}/${f.version.versionId}`;f.actor(undefined);expect((await f.raw(route)).status).toBe(401);f.actor({...tenant,workspaceId:'other'});expect((await f.raw(route)).status).toBe(404);f.actor(tenant);const stored=f.store.records.get(share.id)!;f.store.records.put({...stored,expiresAt:Date.now()-1});expect((await f.raw(route)).status).toBe(404);expect((await f.api('shares/'+share.id)).status).toBe(404);f.store.records.put(stored);await f.api('shares/'+share.id,'DELETE');expect((await f.raw(route)).status).toBe(404);});
 it('版本内容被篡改时拒绝下载和再次分享',async()=>{const f=await artifactFixture();const share=(await f.api('shares','POST',{taskId:'task-a',public:true,confirmPublic:true,includeFiles:true,confirmFiles:true,files:[f.selection]})).data;writeFileSync(f.version.path,'篡改字节');f.actor(undefined);expect((await f.raw(`shares/${share.id}/files/${f.art.artifactId}/${f.version.versionId}`)).status).toBe(409);f.actor(tenant);expect((await f.api('shares','POST',{taskId:'task-a',includeFiles:true,confirmFiles:true,files:[f.selection]})).status).toBe(409);});
 it('ZIP包含manifest、脱敏对话轨迹及真实产物，默认排除输入原件和工具原始参数',async()=>{const f=await artifactFixture();const input=join(f.dir,'source.txt');writeFileSync(input,'输入原件');f.inputFiles.push({fileId:'input-a',name:'source.txt',path:input,sha256:createHash('sha256').update('输入原件').digest('hex')});const response=await f.raw('handoff','POST',{taskId:'task-a',files:[f.selection],note:'sk-'+ 'c'.repeat(24)});expect(response.status).toBe(200);expect(response.headers.get('content-type')).toBe('application/zip');const zip=unzipSync(new Uint8Array(await response.arrayBuffer()));expect(Object.keys(zip)).toEqual(expect.arrayContaining(['manifest.json','conversation.json','operations.json']));const artifactName=Object.keys(zip).find(n=>n.startsWith('artifacts/'))!;expect(strFromU8(zip[artifactName]!)).toBe('<h1>真实产物</h1>');expect(Object.keys(zip).some(n=>n.startsWith('inputs/'))).toBe(false);const transcript=strFromU8(zip['conversation.json']!),manifest=JSON.parse(strFromU8(zip['manifest.json']!));expect(transcript).toContain('<REDACTED>');expect(transcript).not.toContain('ghp_');expect(transcript).not.toContain('github_pat_');expect(manifest.note).toBe('<REDACTED>');expect(strFromU8(zip['operations.json']!)).not.toContain('do-not-export-raw-args');expect(manifest.files.find((f:any)=>f.kind==='artifact').sha256).toBe(f.version.sha256);});
 it('输入原件只取回调授权ID，必须确认且读取时核验hash，不接受请求路径',async()=>{const f=await artifactFixture();const input=join(f.dir,'source.txt');writeFileSync(input,'allowed input');f.inputFiles.push({fileId:'input-a',name:'source.txt',path:input,sha256:createHash('sha256').update('allowed input').digest('hex')});expect((await f.api('handoff','POST',{taskId:'task-a',includeInputs:true,inputIds:['input-a']})).status).toBe(400);expect((await f.api('handoff','POST',{taskId:'task-a',includeInputs:true,confirmInputs:true,inputIds:['/etc/passwd'],path:input})).status).toBe(404);const options=(await f.api('handoff/options?taskId=task-a')).data;expect(options.inputs[0].path).toBeUndefined();const response=await f.raw('handoff','POST',{taskId:'task-a',includeInputs:true,confirmInputs:true,inputIds:['input-a']});expect(response.status).toBe(200);const zip=unzipSync(new Uint8Array(await response.arrayBuffer()));expect(strFromU8(zip['inputs/001_source.txt']!)).toBe('allowed input');writeFileSync(input,'changed');expect((await f.api('handoff','POST',{taskId:'task-a',includeInputs:true,confirmInputs:true,inputIds:['input-a']})).status).toBe(409);f.actor(undefined);expect((await f.raw('handoff','POST',{taskId:'task-a'})).status).toBe(401);});
});
