import type { PlatformTool } from "@tao/core";
import { createSpreadsheetEditTool } from "./spreadsheet.ts";
import { writePresentation, type PresentationSpec } from "./presentation.ts";
import { readExtendedFile, mergePdf } from "./extended-readers.ts";
import { fillDocumentTemplate } from "./document-template.ts";
export function createExtendedOfficeToolset({workspace}:{workspace:string}):PlatformTool[]{return[
 createSpreadsheetEditTool(workspace),
 {name:"write_presentation",label:"生成可编辑演示稿",replay:"never",description:"生成原生可编辑PPTX，支持主题字体颜色、每页标题和正文、PNG/JPEG本地图片、原生柱状/折线/饼图及演讲备注。图片路径须在工作区。",parameters:{type:"object",properties:{outputName:{type:"string"},title:{type:"string"},theme:{type:"object",properties:{font:{type:"string"},accent:{type:"string"},background:{type:"string"},text:{type:"string"}}},slides:{type:"array",minItems:1,maxItems:100,items:{type:"object",properties:{title:{type:"string"},body:{type:"array",items:{type:"string"}},notes:{type:"string"},imagePath:{type:"string"},chart:{type:"object",properties:{type:{type:"string",enum:["bar","line","pie"]},title:{type:"string"},categories:{type:"array",items:{type:"string"}},series:{type:"array",items:{type:"object",properties:{name:{type:"string"},values:{type:"array",items:{type:"number"}}},required:["name","values"]}}},required:["type","categories","series"]}},required:["title"]}}},required:["outputName","title","slides"]},async execute({args,signal,report}){signal.throwIfAborted();report("正在生成原生可编辑演示稿");const outputPath=await writePresentation(workspace,args as PresentationSpec);return{text:"演示稿已生成，文字、图表和图片均可在PowerPoint/WPS中编辑",details:{outputPath}};}},
 {name:"read_file",label:"读取多格式文件",replay:"safe",description:"分页读取PDF文本层、PPTX幻灯片、RTF、代码和UTF-8文本，或安全列出ZIP目录和读取其文本条目。扫描PDF返回requiresOcr；不执行代码或解压到磁盘。offset从0开始；PDF单位为页，PPTX为幻灯片，代码为行。勿将一批内容当作整份文件。",parameters:{type:"object",properties:{path:{type:"string"},offset:{type:"integer",minimum:0},limit:{type:"integer",minimum:1,maximum:100},entry:{type:"string",description:"ZIP内文本条目名称，省略则列目录"}},required:["path"]},async execute({args,signal}){signal.throwIfAborted();const r=await readExtendedFile(workspace,args as Parameters<typeof readExtendedFile>[1]);return{text:[r.text,...r.warnings,r.nextOffset===null?"本批已到文件末尾。":`还有未读内容，请用offset=${r.nextOffset}继续。`].join("\n"),details:r};}},
 {name:"merge_pdf",label:"合并PDF",replay:"never",description:"按输入顺序合并2至20份PDF为新文件，保留页面内容，不覆盖原件。总页数上限500；不保留原文档的签名、书签和交互表单。",parameters:{type:"object",properties:{paths:{type:"array",minItems:2,maxItems:20,items:{type:"string"}},outputName:{type:"string"}},required:["paths","outputName"]},async execute({args,signal,report}){signal.throwIfAborted();report("正在合并PDF页面");const outputPath=await mergePdf(workspace,args as Parameters<typeof mergePdf>[1]);return{text:"PDF合并完成",details:{outputPath}};}},
 {name:"fill_document_template",label:"填充Word模板",replay:"never",description:"填充DOCX模板字段{名称}及循环{#列表}...{/列表}，保留原有样式、页眉页脚和表格；字段缺失会报错。data为字段对象，仅使用显式提供的数据，不执行表达式。另存新文件。",parameters:{type:"object",properties:{path:{type:"string"},outputName:{type:"string"},data:{type:"object",additionalProperties:true}},required:["path","outputName","data"]},async execute({args,signal,report}){signal.throwIfAborted();report("正在填充Word模板并保留原格式");const outputPath=await fillDocumentTemplate(workspace,args as Parameters<typeof fillDocumentTemplate>[1]);return{text:"模板文档已生成，原模板未修改",details:{outputPath}};}}
];}
// 嵌套数组路径由工具内部readWorkspaceFile逐个校验，不能依赖只读顶层参数的权限门。
export const EXTENDED_OFFICE_TOOL_POLICIES=[{tool:"edit_spreadsheet",pathParams:["path"]},{tool:"write_presentation"},{tool:"read_file",pathParams:["path"]},{tool:"merge_pdf"},{tool:"fill_document_template",pathParams:["path"]}] as const;
