(function(){'use strict';var platformAdmin=false;var roles={MEMBER:'成员',WORKSPACE_ADMIN:'工作区管理员',TENANT_ADMIN:'租户管理员',PLATFORM_ADMIN:'平台管理员'};var csrf='',revision=0,fields=[],current={},host=document.getElementById('configuration');
function el(tag,text){var n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
async function api(method,path,body){var token=sessionStorage.getItem('tao.control.token')||localStorage.getItem('tao.token')||'';var r=await fetch(path,{method:method,headers:Object.assign({'Content-Type':'application/json','X-CSRF-Token':csrf},token?{Authorization:'Bearer '+token}:{}),body:body===undefined?undefined:JSON.stringify(body)});var d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}
function status(s){document.getElementById('configStatus').textContent=s;}
function button(text,fn){var b=el('button',text);b.type='button';b.addEventListener('click',async function(){b.disabled=true;try{await fn();}catch(e){status(e.message);}finally{b.disabled=false;}});return b;}
function render(data){revision=data.revision;current=data.draft||data.values;host.replaceChildren();var groups={};fields.forEach(function(f){if(f.readOnly)return;var section=groups[f.group];if(!section){section=el('details');section.open=['model','limits'].includes(f.group);section.className='card settings-group';section.appendChild(el('summary',({model:'模型服务',limits:'限流与配额',knowledge:'知识库',search:'联网搜索',extensions:'扩展与子智能体',observability:'观测',evaluation:'评测',branding:'品牌外观',deployment:'部署'})[f.group]||f.group));host.appendChild(section);groups[f.group]=section;}
var label=el('label',f.label),input;if(f.options){input=el('select');input.appendChild(el('option',''));f.options.forEach(function(v){var o=el('option',v);o.value=v;input.appendChild(o);});}else input=el('input');input.name=f.key;input.dataset.kind=f.type;if(f.secret){input.type='password';input.autocomplete='new-password';input.placeholder=(data.draftSecrets||data.secrets)[f.key]?'已配置，留空保持':'尚未配置';input.dataset.secret='true';}else if(f.type==='boolean'){input.type='checkbox';input.checked=current[f.key]===true;}else{if(input.tagName==='INPUT')input.type=f.type==='number'?'number':'text';input.value=current[f.key]===undefined?'':current[f.key];if(f.min!==undefined)input.min=f.min;if(f.max!==undefined)input.max=f.max;input.step='any';}label.appendChild(input);if(f.key.endsWith('_PROVIDER')&&f.group==='model'){input.addEventListener('change',function(){var base=host.querySelector('[name="'+f.key.replace('_PROVIDER','_BASE_URL')+'"]'),urls={deepseek:'https://api.deepseek.com/v1',qwen:'https://dashscope.aliyuncs.com/compatible-mode/v1'};if(base&&!base.value&&urls[input.value])base.value=urls[input.value];});}if(f.key==='BRAND_LOGO_URL'){var upload=el('input');upload.type='file';upload.accept='image/png,image/jpeg,image/webp';upload.addEventListener('change',async function(){try{var fd=new FormData();fd.append('file',upload.files[0]);var r=await fetch('/api/control/branding/logo',{method:'POST',headers:{'X-CSRF-Token':csrf},body:fd});var d=await r.json();if(!r.ok)throw Error(d.error);input.value=d.url;status('图片已上传，请保存并应用配置');}catch(e){status(e.message);}});label.appendChild(upload);}if(f.secret){var clear=el('input');clear.type='checkbox';clear.dataset.clear=f.key;var clearLabel=el('label','清除此密钥');clearLabel.appendChild(clear);label.appendChild(clearLabel);}section.appendChild(label);});status('生效版本 '+data.activeRevision+' · 当前版本 '+revision+(data.draft?' · 有未应用草稿':''));}
async function reload(){render(await api('GET','/api/control/settings'));}
async function save(){var values={};host.querySelectorAll('[name]').forEach(function(i){if(i.dataset.secret==='true'){if(i.value)values[i.name]=i.value;}else values[i.name]=i.type==='checkbox'?i.checked:i.value===''?null:i.dataset.kind==='number'?Number(i.value):i.value;});host.querySelectorAll('[data-clear]').forEach(function(i){if(i.checked)values[i.dataset.clear]=null;});render(await api('PUT','/api/control/settings/draft',{values:values,expectedRevision:revision}));status('草稿已保存。连接测试通过后点击应用；运行中的任务不会被中断。');}
async function accounts(){var box=document.getElementById('accountsList');box.replaceChildren();var data=await api('GET','/api/control/accounts');data.accounts.forEach(function(a){var row=el('div');row.className='account-row';row.appendChild(el('span',a.name+' · '+a.username+' · '+roles[a.role]+' · '+(a.enabled?'启用':'停用')));var name=el('input');name.value=a.name;var workspace=el('input');workspace.value=a.workspaceId;var role=el('select');['MEMBER','WORKSPACE_ADMIN','TENANT_ADMIN','PLATFORM_ADMIN'].filter(v=>platformAdmin||v!=='PLATFORM_ADMIN').forEach(function(v){var o=el('option',roles[v]);o.value=v;role.appendChild(o);});role.value=a.role;row.append(name,workspace,role);row.appendChild(button('保存账号',async()=>{await api('PATCH','/api/control/accounts/'+encodeURIComponent(a.id),{name:name.value,workspaceId:workspace.value,role:role.value});await accounts();}));row.appendChild(button(a.enabled?'停用':'启用',async()=>{if(!await App.Dialog.confirm({title:a.enabled?'停用账号':'启用账号',description:'停用会撤销现有会话并取消在途任务。',danger:a.enabled}))return;await api('PATCH','/api/control/accounts/'+encodeURIComponent(a.id),{enabled:!a.enabled});await accounts();}));row.appendChild(button('撤销会话',async()=>{if(!await App.Dialog.confirm({title:'撤销会话',description:'该账号需要重新登录，当前任务会取消。',danger:true}))return;await api('POST','/api/control/accounts/'+encodeURIComponent(a.id)+'/revoke-sessions',{});status('会话已撤销');}));var pass=el('input');pass.type='password';pass.placeholder='新密码（至少12字符）';row.appendChild(pass);row.appendChild(button('重置密码',async()=>{if(!await App.Dialog.confirm({title:'重置登录密码',description:'旧密码、令牌和会话立即失效。',danger:true}))return;await api('POST','/api/control/accounts/'+encodeURIComponent(a.id)+'/reset-credential',{password:pass.value});pass.value='';status('密码已重置');}));box.appendChild(row);});}
function table(columns,rows){var t=el('table'),head=el('tr');columns.forEach(c=>head.appendChild(el('th',c)));t.appendChild(head);rows.forEach(function(values){var row=el('tr');values.forEach(v=>row.appendChild(el('td',v)));t.appendChild(row);});return t;}
async function observe(){var d=await api('GET','/api/control/observability'),box=document.getElementById('observabilityData');box.replaceChildren();box.appendChild(el('p','任务 '+d.summary.tasks+' · 成功 '+d.summary.succeeded+' · 失败 '+d.summary.failed));box.appendChild(table(['模型','开始时间','耗时毫秒','首字毫秒','Token','状态'],d.modelRequests.map(r=>[r.model,new Date(r.at).toLocaleString(),r.durationMs,r.firstTokenMs===null?'—':r.firstTokenMs,r.tokens,r.status])));box.appendChild(el('h3','任务追踪'));d.tasks.forEach(function(t){box.appendChild(button((t.title||t.taskId)+' · '+t.status,async()=>{var trace=await api('GET','/api/control/traces/'+t.taskId);var view=el('details');view.open=true;view.appendChild(el('summary','执行轨迹'));view.appendChild(table(['时间','类型','操作或状态','说明'],trace.events.map(e=>[new Date(e.at).toLocaleTimeString(),e.type,e.action||e.to||e.model,e.detail||e.reason||''])));box.appendChild(view);}));});if(platformAdmin){try{var checks=await api('GET','/api/control/connections');box.appendChild(el('h3','已发布配置连接验证'));checks.connections.forEach(function(c){box.appendChild(el('p',({model:'旗舰模型',lite:'轻量模型',evaluation:'评测模型',embedding:'嵌入模型',search:'联网搜索',mcp:'MCP'})[c.type]+'：'+({unconfigured:'未配置',unverified:'未验证',available:'最近测试可用',failed:'最近测试失败'})[c.status]+(c.checkedAt?' · '+new Date(c.checkedAt).toLocaleString():'')));});}catch(e){box.appendChild(el('p',e.message));}}box.appendChild(el('h3','能力连接状态'));Object.entries(d.capabilities).forEach(function(pair){box.appendChild(el('p',({model:'模型运行',search:'联网搜索',mcp:'MCP',rag:'向量检索',codeExecution:'代码执行',otlp:'观测导出',modelJudge:'模型评审'})[pair[0]]+'：'+(pair[1]?'已配置':'未接通')));});}

async function evaluations(){var d=await api('GET','/api/control/evaluations'),box=document.getElementById('evaluationList');box.replaceChildren();var completed=d.runs.filter(r=>r.status!=='running');if(completed.length>1){var base=el('select'),target=el('select');[base,target].forEach(function(select){completed.forEach(r=>{var option=el('option',r.id+' · 配置版本 '+r.revision);option.value=r.id;select.appendChild(option);});});base.setAttribute('aria-label','基线运行');target.setAttribute('aria-label','对比运行');target.selectedIndex=1;box.append(base,target,button('对比两次运行',async()=>{var comparison=await api('GET','/api/control/evaluations/compare?'+new URLSearchParams({base:base.value,target:target.value}));var view=el('div');view.appendChild(table(['用例','变化','基线','对比'],comparison.cases.map(c=>[c.query,({unchanged:'无变化',improved:'改善',regressed:'退化',unverified:'未完成，无法判断'})[c.change],c.base?(c.base.passed?'通过':'未通过'):'未执行',c.target?(c.target.passed?'通过':'未通过'):'未执行'])));box.appendChild(view);}));}d.datasets.forEach(function(ds){var row=el('div',ds.name+'（'+ds.cases.length+'条） ');row.appendChild(button('运行评测（消耗模型额度）',async()=>{await api('POST','/api/control/evaluations/runs',{datasetId:ds.id});await evaluations();}));box.appendChild(row);});d.runs.forEach(function(r){var row=el('details');row.appendChild(el('summary',r.id+' · '+r.status+' · '+r.results.length+'条结果 · Token '+(r.tokens||0)+' · 费用 '+(r.costYuan==null?'未知':r.costYuan.toFixed(4)+'元')));r.results.forEach(function(result,index){var item=el('article');item.appendChild(el('h4',result.query));item.appendChild(el('p',result.answer));if(result.tags?.length)item.appendChild(el('p','标签：'+result.tags.join('、')));(result.checks||[]).forEach(c=>item.appendChild(el('p',({task_status:'任务状态',keyword:'关键词',json_key:'JSON字段',tool_success:'工具成功执行'})[c.rule]+' · '+c.expected+'：'+(c.passed?'通过':'未通过'))));item.appendChild(el('p','规则评分：'+(result.passed?'通过':'未通过')+'；人工复核：'+(result.review?result.review.result:'未复核')));['pass','fail'].forEach(function(value){item.appendChild(button(value==='pass'?'复核通过':'复核未通过',async()=>{await api('POST','/api/control/evaluations/runs/'+r.id+'/review',{index:index,result:value});await evaluations();}));});row.appendChild(item);});if(r.status==='running')row.appendChild(button('取消后续用例',async()=>{await api('POST','/api/control/evaluations/runs/'+r.id+'/cancel',{});await evaluations();}));box.appendChild(row);});}
document.getElementById('suspendModel').addEventListener('click',async()=>{if(!await App.Dialog.confirm({title:'暂停模型调用',description:'立即阻止后续模型请求并取消在途任务。应用配置后才能恢复。',danger:true}))return;try{var r=await api('POST','/api/control/model/suspend',{});status(r.message);}catch(e){status(e.message);}});
document.getElementById('exportConfig').addEventListener('click',async()=>{try{var data=await api('GET','/api/control/settings'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),link=el('a');link.href=url;link.download='脱敏配置.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){status(e.message);}});
document.getElementById('saveConfig').addEventListener('click',()=>save().catch(e=>status(e.message)));
document.getElementById('applyConfig').addEventListener('click',async()=>{try{render(await api('POST','/api/control/settings/apply',{expectedRevision:revision}));window.dispatchEvent(new Event('tao:branding-changed'));status('配置已应用，新任务使用新配置。');}catch(e){status(e.message);}});
document.querySelectorAll('[data-test-connection]').forEach(function(b){b.addEventListener('click',async()=>{b.disabled=true;try{await save();var r=await api('POST','/api/control/connections/test',{type:b.dataset.testConnection});status(r.message);}catch(e){status(e.message);}finally{b.disabled=false;}});});
document.getElementById('newAccount').addEventListener('submit',async function(e){e.preventDefault();var d=Object.fromEntries(new FormData(this));try{await api('POST','/api/control/accounts',d);this.reset();await accounts();status('账号已创建');}catch(e){status(e.message);}});
function addCase(){var row=el('div');row.className='eval-case';var q=el('textarea');q.placeholder='用户输入';q.required=true;var expected=el('input');expected.placeholder='预期包含的关键词，逗号分隔';expected.dataset.field='expected';var extras=['tags','jsonKeys','tools'].map(function(key){var i=el('input');i.dataset.field=key;i.placeholder=({tags:'标签，逗号分隔',jsonKeys:'要求JSON包含的顶层字段，逗号分隔',tools:'要求成功执行的工具名，逗号分隔'})[key];i.setAttribute('aria-label',i.placeholder);return i;});row.append(q,expected,...extras,button('移除',async()=>row.remove()));document.getElementById('datasetCases').appendChild(row);}document.getElementById('addEvalCase').addEventListener('click',addCase);addCase();
document.getElementById('newDataset').addEventListener('submit',async function(e){e.preventDefault();try{await api('POST','/api/control/evaluations/datasets',{name:this.elements.name.value,cases:Array.from(document.querySelectorAll('.eval-case')).map(function(row){var value={query:row.querySelector('textarea').value};row.querySelectorAll('[data-field]').forEach(i=>value[i.dataset.field]=i.value.replaceAll('，',',').split(',').map(s=>s.trim()).filter(Boolean));return value;})});await evaluations();status('评测集已保存');}catch(e){status(e.message);}});
document.getElementById('refreshObserve').addEventListener('click',()=>observe().catch(e=>status(e.message)));
document.getElementById('refreshEvaluations').addEventListener('click',()=>evaluations().catch(e=>status(e.message)));
document.getElementById('historyConfig').addEventListener('click',async()=>{try{var d=await api('GET','/api/control/settings/history'),box=document.getElementById('configHistory');box.replaceChildren();d.history.forEach(function(r){var row=el('div','版本 '+r.revision+' · '+r.updatedAt+' · '+r.actor);row.appendChild(button('回退非密钥配置',async()=>{render(await api('POST','/api/control/settings/rollback',{revision:r.revision,expectedRevision:revision}));status('非密钥配置已回退，密钥保持当前值');}));box.appendChild(row);});}catch(e){status(e.message);}});

async function knowledge(){var box=document.getElementById('knowledgeAdminData');var state=await api('GET','/api/knowledge/status'),d=await api('GET','/api/knowledge');box.replaceChildren();box.appendChild(el('p','检索模式：'+state.rag.mode+' · 已索引 '+state.rag.indexedDocuments+' · 待重建 '+state.rag.pendingDocuments));d.documents.forEach(function(doc){var row=el('div',doc.name+' · '+({ready:'就绪',needs_reindex:'待重建',disabled:'未启用向量检索'})[doc.vectorStatus]);row.appendChild(button('重建索引',async()=>{var result=await api('POST','/api/knowledge/'+doc.documentId+'/reindex',{});row.appendChild(el('span',' 作业已提交'));var jobId=result.job.jobId;var check=button('查看重建进度',async()=>{var r=await api('GET','/api/knowledge/jobs/'+jobId);status('索引作业：'+r.job.status+(r.job.error?' · '+r.job.error:''));if(r.job.status==='ready')await knowledge();});row.appendChild(check);}));box.appendChild(row);});}
document.getElementById('refreshKnowledge').addEventListener('click',()=>knowledge().catch(e=>status(e.message)));
api('GET','/api/auth/me').then(async function(me){csrf=me.csrf||'';platformAdmin=me.role==='PLATFORM_ADMIN';if(platformAdmin){var option=el('option','平台管理员');option.value='PLATFORM_ADMIN';document.querySelector('#newAccount [name=role]').appendChild(option);}var schema=await api('GET','/api/control/schema');fields=schema.fields;if(schema.canConfigure)await reload();else{document.getElementById('settings').hidden=true;status('部署配置仅对部署管理员开放');}await accounts();await observe();await evaluations();await knowledge();}).catch(e=>status(e.message));
})();
