import {readFileSync,writeFileSync,lstatSync} from 'node:fs';
import {extname,join} from 'node:path';
import {randomUUID} from 'node:crypto';
import type {PlatformTool,RunnerSpec} from '@tao/core';
import {outboundFetch} from './admin-network.ts';
import {checkEndpoint} from './admin-integrations.ts';
import type {Values} from './admin-settings.ts';
import {checkedFile} from './workspace-services.ts';
export function imageAttachments(paths:readonly string[]):NonNullable<RunnerSpec['images']>{const images:NonNullable<RunnerSpec['images']>[number][]=[];let total=0;for(const path of paths){if(!['.png','.jpg','.jpeg','.webp'].includes(extname(path).toLowerCase()))continue;const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>5*1024*1024)throw Error('图片必须是小于5MB的普通文件');total+=stat.size;if(total>5*1024*1024||images.length>=4)throw Error('每轮最多4张图片且合计不超过5MB');const b=readFileSync(path);let mimeType='';if(b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))mimeType='image/png';else if(b[0]===255&&b[1]===216&&b[2]===255)mimeType='image/jpeg';else if(b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP')mimeType='image/webp';else throw Error('图片内容与格式不符');images.push({type:'image',data:b.toString('base64'),mimeType});}return images;}
export function mediaCapabilities(v:Values){return {imageGeneration:!!(v.IMAGE_ENABLED==='true'&&v.IMAGE_API_URL&&v.IMAGE_MODEL&&v.IMAGE_API_KEY),transcription:!!(v.AUDIO_ENABLED==='true'&&v.AUDIO_API_URL&&v.AUDIO_MODEL&&v.AUDIO_API_KEY)};}
export function mediaTools(v:Values,workspace:string):PlatformTool[]{const tools:PlatformTool[]=[];
 if(mediaCapabilities(v).imageGeneration)tools.push({name:'generate_image',label:'生成图片',description:'调用已配置图像模型生成海报或插图，交付真实PNG。不要声称照片内容真实发生。',parameters:{type:'object',properties:{prompt:{type:'string',maxLength:4000},size:{type:'string',enum:['1024x1024','1024x1536','1536x1024']}},required:['prompt']},replay:'never',async execute({args,signal,report}){const a=args as any;if(typeof a.prompt!=='string'||!a.prompt.trim()||a.prompt.length>4000)throw Error('图片描述须为1至4000字');const url=checkEndpoint(v.IMAGE_API_URL!).href.replace(/\/$/,'')+'/images/generations';report('正在生成图片');const r=await outboundFetch(v.NETWORK_ALLOWED_CIDRS,16*1024*1024)(url,{method:'POST',headers:{Authorization:'Bearer '+v.IMAGE_API_KEY,'Content-Type':'application/json'},signal:AbortSignal.any([signal,AbortSignal.timeout(120000)]),body:JSON.stringify({model:v.IMAGE_MODEL,prompt:a.prompt,n:1,size:a.size||'1024x1024',response_format:'b64_json'})});if(!r.ok)throw Error('图像服务返回状态'+r.status);const d:any=await r.json();const encoded=d.data?.[0]?.b64_json;if(typeof encoded!=='string'||encoded.length>14*1024*1024)throw Error('图像服务未返回受支持的base64图片');const bytes=Buffer.from(encoded,'base64');if(bytes.length>10*1024*1024||!bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))throw Error('图像服务返回的文件不是合法大小的PNG');const outputPath=join(workspace,'generated-'+randomUUID()+'.png');writeFileSync(outputPath,bytes,{flag:'wx'});return {text:'图片已生成并交付',details:{outputPath}};}});
 if(mediaCapabilities(v).transcription)tools.push({name:'transcribe_audio',label:'转录音频',description:'把用户引用的录音转为文字，用于会议纪要；只处理当前任务授权文件。',parameters:{type:'object',properties:{path:{type:'string'},language:{type:'string'}},required:['path']},replay:'never',async execute({args,signal,report}){const a=args as any,path=checkedFile(workspace,String(a.path));const bytes=readFileSync(path);if(bytes.length>8*1024*1024)throw Error('录音超过8MB，请先切分');if(!['.mp3','.wav','.m4a','.ogg','.webm'].includes(extname(path).toLowerCase()))throw Error('不支持的音频格式');const form=new FormData();form.set('model',v.AUDIO_MODEL!);form.set('file',new Blob([bytes]),'audio'+extname(path));if(a.language)form.set('language',String(a.language).slice(0,10));report('正在转录录音');const r=await outboundFetch(v.NETWORK_ALLOWED_CIDRS)(checkEndpoint(v.AUDIO_API_URL!).href.replace(/\/$/,'')+'/audio/transcriptions',{method:'POST',headers:{Authorization:'Bearer '+v.AUDIO_API_KEY},body:form,signal:AbortSignal.any([signal,AbortSignal.timeout(120000)])});if(!r.ok)throw Error('转录服务返回状态'+r.status);const d:any=await r.json();if(typeof d.text!=='string')throw Error('转录服务没有返回文字');const text=d.text.slice(0,200000),outputPath=join(workspace,'录音转写-'+randomUUID()+'.txt');writeFileSync(outputPath,text,{flag:'wx'});return {text,details:{outputPath}};}});
 return tools;
}

/** 可选的文本审核服务；启用后失败关闭，不将请求或密钥写日志。 */
export function textModerator(v:Values):((text:string,signal:AbortSignal)=>Promise<void>)|undefined{
 if(v.MODERATION_ENABLED!=='true')return undefined;
 return async(text,signal)=>{if(!v.MODERATION_API_URL||!v.MODERATION_API_KEY)throw Error('文本审核服务尚未完整配置');if(!text.trim())return;if(text.length>200000)throw Error('内容超过审核服务长度限制');const r=await outboundFetch(v.NETWORK_ALLOWED_CIDRS,1024*1024)(checkEndpoint(v.MODERATION_API_URL).href.replace(/\/$/,'')+'/moderations',{method:'POST',headers:{Authorization:'Bearer '+v.MODERATION_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({input:text,...(v.MODERATION_MODEL?{model:v.MODERATION_MODEL}:{})}),signal:AbortSignal.any([signal,AbortSignal.timeout(15000)])});if(!r.ok)throw Error('文本审核服务暂不可用');const d:any=await r.json();if(!Array.isArray(d.results)||!d.results.length||d.results.some((x:any)=>typeof x.flagged!=='boolean'))throw Error('审核服务响应无效');if(d.results.some((x:any)=>x.flagged))throw Error('内容未通过已配置的文本审核规则');};
}
