import {unzipSync,strFromU8} from 'fflate';
import {randomUUID,createHash} from 'node:crypto';
import {existsSync,mkdirSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import type {IncomingMessage,ServerResponse} from 'node:http';
import type {TenantContext,PlatformTool} from '@tao/core';
import {AdminError,atomicJson} from './admin-settings.ts';
import {readJsonBody,sendJson,sendError,type Principal} from './app.ts';
import type {SandboxManager} from './sandbox/manager.ts';
export interface SkillPackage {id:string;tenant:TenantContext;name:string;description:string;instructions:string;enabled:boolean;hash:string;createdAt:number;files:Record<string,string>;scripts:{path:string;language:string}[];}
function scoped(a:TenantContext,b:TenantContext){return a.tenantId===b.tenantId&&a.workspaceId===b.workspaceId&&a.userId===b.userId;}
export class SkillPackages {
 private readonly path:string;private items:SkillPackage[]=[];
 constructor(root:string){mkdirSync(join(root,'.skill-packages'),{recursive:true,mode:0o700});this.path=join(root,'.skill-packages','packages.json');if(existsSync(this.path))this.items=JSON.parse(readFileSync(this.path,'utf8'));}
 list(t:TenantContext){return this.items.filter(s=>scoped(s.tenant,t)).map(({files,instructions,...s})=>s);}
 get(t:TenantContext,id:string){return this.items.find(s=>s.id===id&&scoped(s.tenant,t));}
 import(t:TenantContext,encoded:string){if(typeof encoded!=='string'||encoded.length>7*1024*1024)throw new AdminError(400,'技能包最大5MB');const bytes=Buffer.from(encoded,'base64');let total=0,count=0;const seen=new Set<string>();const entries=unzipSync(bytes,{filter:f=>{if(++count>100||f.originalSize>5*1024*1024||(total+=f.originalSize)>10*1024*1024)throw new AdminError(400,'技能包解压体积或文件数量超限');if(f.name.includes('\\')||f.name.startsWith('/')||f.name.split('/').some(s=>['..','.','__proto__','constructor','prototype'].includes(s))||/[\x00-\x1f]/.test(f.name)||seen.has(f.name))throw new AdminError(400,'技能包路径无效');seen.add(f.name);return !f.name.endsWith('/');}});const names=Object.keys(entries),mains=names.filter(n=>n==='SKILL.md'||/^[^/]+\/SKILL.md$/.test(n));if(mains.length!==1)throw new AdminError(400,'技能包必须包含唯一根目录SKILL.md');const main=mains[0]!,prefix=main.slice(0,-8);if(names.some(n=>!n.startsWith(prefix)))throw new AdminError(400,'技能包须位于同一根目录');const instructions=strFromU8(entries[main]!);if(instructions.length>64000)throw new AdminError(400,'SKILL.md过长');const header=/^---\r?\n([\s\S]*?)\r?\n---/.exec(instructions)?.[1];if(!header)throw new AdminError(400,'SKILL.md缺少YAML元数据');const field=(key:string)=>new RegExp('^'+key+':\\s*["\x27]?([^\\r\\n"\x27]+)','m').exec(header)?.[1]?.trim()||'';const name=field('name'),description=field('description');if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name)||name.length>64||!description||description.length>1024)throw new AdminError(400,'技能名称或描述不符合Agent Skills规范');if(prefix&&prefix!==name+'/')throw new AdminError(400,'技能目录名应与name一致');const files:Record<string,string>=Object.create(null),scripts:SkillPackage['scripts']=[];for(const n of names){const path=n.slice(prefix.length);files[path]=Buffer.from(entries[n]!).toString('base64');if(path.startsWith('scripts/')){const language=path.endsWith('.py')?'python':path.endsWith('.js')?'javascript':path.endsWith('.sh')?'bash':'';if(language)scripts.push({path,language});}}if(this.list(t).length>=100)throw new AdminError(400,'个人技能包已达100个上限');const item:SkillPackage={id:'pack-'+randomUUID(),tenant:t,name,description,instructions,enabled:true,hash:createHash('sha256').update(bytes).digest('hex'),createdAt:Date.now(),files,scripts};this.items.push(item);this.save();return this.list(t).find(s=>s.id===item.id)!;}
 update(t:TenantContext,id:string,enabled:boolean){const s=this.get(t,id);if(!s)throw new AdminError(404,'技能包不存在');s.enabled=enabled;this.save();}
 remove(t:TenantContext,id:string){if(!this.get(t,id))throw new AdminError(404,'技能包不存在');this.items=this.items.filter(s=>s.id!==id);this.save();}
 private save(){atomicJson(this.path,this.items);}
 tool(t:TenantContext,taskId:string,dir:string,id:string,sandbox:SandboxManager):PlatformTool {const s=this.get(t,id);if(!s?.enabled)throw new AdminError(400,'技能包不存在或已停用');return {name:'run_skill_script',label:'执行所选技能脚本',replay:'never',description:'执行用户为本任务选定的技能包脚本。仅限清单中的脚本，始终先确认，再在独立沙箱运行；不会在宿主安装或执行。可用脚本：'+s.scripts.map(x=>x.path).join(', '),parameters:{type:'object',properties:{path:{type:'string',enum:s.scripts.map(x=>x.path)},args:{type:'array',maxItems:16,items:{type:'string',maxLength:1024}}},required:['path']},async execute({args,signal,report}){const a=args as any;const script=s.scripts.find(x=>x.path===a.path);if(!script||!Array.isArray(a.args??[])||(a.args??[]).some((x:unknown)=>typeof x!=='string'||x.length>1024))throw Error('技能脚本或参数无效');await sandbox.provision(t,taskId,dir,Object.fromEntries(Object.entries(s.files).map(([name,data])=>['skills/'+id+'/'+name,Buffer.from(data,'base64')])),signal);const quote=(x:string)=>"'"+x.replaceAll("'","'\\''")+"'",command=[script.language==='python'?'python3':script.language==='javascript'?'node':'bash','/workspace/skills/'+id+'/'+script.path,...(a.args??[])].map(quote).join(' ');const execute=sandbox.tools(t,taskId,dir).find(x=>x.name==='sandbox_execute');if(!execute)throw Error('请管理员启用沙箱');return execute.execute({tenant:t,taskId,args:{language:'bash',code:command},signal,report});}};}
}
export function createSkillPackageHandler(deps:{store:SkillPackages;authenticate:(req:IncomingMessage)=>Promise<Principal|undefined>}){return async(req:IncomingMessage,res:ServerResponse)=>{const parts=new URL(req.url||'/','http://local').pathname.split('/').filter(Boolean);if(parts[0]!=='api'||parts[1]!=='skill-packages')return false;try{const p=await deps.authenticate(req);if(!p)throw new AdminError(401,'请先登录');if(req.method==='GET'&&parts.length===2)sendJson(res,200,{packages:deps.store.list(p.tenant)});else if(req.method==='POST'&&parts.length===2){const b=await readJsonBody(req,8*1024*1024);if(!b.ok)throw new AdminError(400,b.reason);sendJson(res,201,deps.store.import(p.tenant,(b.value as any).archiveBase64));}else if(req.method==='PATCH'&&parts[2]){const b=await readJsonBody(req,8*1024*1024);if(!b.ok||typeof (b.value as any).enabled!=='boolean')throw new AdminError(400,'请指定enabled');deps.store.update(p.tenant,parts[2],(b.value as any).enabled);sendJson(res,200,{ok:true});}else if(req.method==='DELETE'&&parts[2]){deps.store.remove(p.tenant,parts[2]);sendJson(res,200,{ok:true});}else throw new AdminError(405,'不支持的操作');}catch(e){sendError(res,e instanceof AdminError?e.status:400,e instanceof AdminError?e.message:'技能包处理失败');}return true;};}
